name: boilerplate_flutter
description: Flutter Boilerplate with Bloc Pattern

publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_i18n: ^0.32.4
  flutter_localizations:
    sdk: flutter
  go_router: ^4.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/flutter_i18n/en.json
    - assets/flutter_i18n/ja.json
