name: boilerplate_flutter
description: Flutter Boilerplate with Bloc Pattern

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.2
  flutter_bloc: ^7.0.0
  flutter_i18n: ^0.22.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/flutter_i18n/en.json
    - assets/flutter_i18n/ja.json
